<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="WIN-Q5M9TTPRAOJ" name="testcases.accounts.TC005_MergeAccounts" tests="2" failures="0" timestamp="04 Apr 2018 07:49:49 GMT" time="0.001" errors="1">
  <testcase name="closeBrowser1" time="0.001" classname="testcases.accounts.TC005_MergeAccounts">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at wdMethods.SeMethods.closeBrowser(SeMethods.java:258)
at testcases.leads.LeafTapsMethods.closeBrowser1(LeafTapsMethods.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:533)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- closeBrowser1 -->
  <testcase name="mergeAccounts" time="0.000" classname="testcases.accounts.TC005_MergeAccounts">
    <skipped/>
  </testcase> <!-- mergeAccounts -->
</testsuite> <!-- testcases.accounts.TC005_MergeAccounts -->
